### PR TITLE
Add .ics file creation

### PR DESCRIPTION
**Pull request by Wolferado**
- Added functionality to create .ics _(iCalendar)_ file
- Added file format selection menu, that allows to choose in which format you would like to receive a calendar _(like other selection of departments and courses)_
- Slightly changed .csv header _(all words to uppercase)_
- Typos fixes

### CODE REVIEW

**Comment by tomszir** [comment]
Please add *.ics to .gitignore and remove the data file from the PR

**Comment by tomszir** [comment]
Also you can just use the CalendarEvent class for ics, just add the ics functions under that

**Comment by Wolferado** [comment]
Don't approve just yet. Will tweak some things a little bit later.

UPD: Things are tweaked. Can approve.

**Comment by tomszir** [comment]
Merged

**Comment by tomszir** [comment]
@all-contributors please add @Wolferado for code

**Pull request merged**
